{{- if .Values.istio.enabled -}}
  {{- if .Values.istio.gatewayenabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "chart.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.hosts }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - {{ .Values.istio.hosts }}
---
  {{- end -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.istio.gatewayenabled }}
  hosts:
    - {{ .Values.istio.hosts }}
  gateways:
    - {{ include "chart.fullname" . }}-gateway
  {{ else }}
  hosts:
    - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{ end }}
  http:
    - match:
        - uri:
            prefix: /crm-service/
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{ include "chart.fullname" . }}
            port:
              number: {{ .Values.containerPort }}
  {{- end -}}
