import Head from "next/head";
import styles from "../styles/Home.module.css";
import type { ReactElement } from "react";
import Layout from "components/Layout";
import Image from "next/image";
import homeBanner from "images/homeBanner.png";
import { Button } from "antd";
import { PlayCircleOutlined } from "@ant-design/icons";

export default function Page() {
  return (
    <div className="w-full h-full">
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="w-full h-full">
        <section
          className={`w-full ${styles.banner} bg-center bg-cover bg-no-repeat relative`}
        >
          <div className={`${styles.bannerContainer} absolute`}>
            <h1 className={` text-white font-roboto font-thin`}>
              Powering Flex & Hybrid Workspaces
            </h1>
            <h3 className="text-sm text-white font-roboto mb-6">
              BOSS - Business Operating System for Space - helps you to automate
              workspace processes, manage tenant lifecycles and streamline flex
              & hybrid workspace operations. With BOSS, you can strengthen a
              gratifying customer experience and boost retention.
              <h4 className="text-sm text-white font-roboto mt-1">
                In turn, maximize your business revenue while ensuring accuracy
                and efficiency.
              </h4>
            </h3>
            <div>
              <Button
                type="primary"
                className={`mr-4 text-sm ${styles.leftButton}`}
              >
                What is BOSS
                <PlayCircleOutlined className={styles.playIcon} />
              </Button>
              <Button ghost className={`text-sm ${styles.rightButton}`}>
                Book Free Demo
              </Button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
