import Head from "next/head";
import styles from "../styles/Home.module.css";
import type { ReactElement } from "react";
import Layout from "components/Layout";
import { Button } from "antd";

export default function Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* {/* <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}
        {/* <Button size="large" className="m-4" type="primary">
          ant design button
        </Button> */}
        <div>当前环境变量：{process.env.NEXT_PUBLIC_ENV_VARIABLE}</div> 
      </main>
    </div>
  );
}


