import { useState, useCallback } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import { PlayCircleOutlined } from "@ant-design/icons";
import { Carousel } from "antd";
import Union from "./../svgs/Union.svg";
import ShowMoreIcon from "./../svgs/add-icon.svg";
import {
  HomePageSectionOneData,
  SectionTwoBossFlexData,
  SectionTwoBossTenantEngage,
  HomePageSectionFiveData,
} from "./constant";

export default function Page() {
  const [isShowMore, setIsShowMore] = useState<boolean>(false);
  const handleShowMore = useCallback(() => {
    setIsShowMore(true);
  }, [isShowMore]);

  return (
    <div className="w-full h-full">
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <section
          className={`w-full bg-home-banner maxlg:bg-home-banner-mobile bg-center bg-cover bg-no-repeat lg:flex lg:justify-center lg:py-32 maxlg:pt-32 maxlg:pb-10`}
        >
          <div className={`maxlg:px-4 lg:w-800 xl:w-1122`}>
            <h2
              className={`text-white font-roboto font-thin lg:text-7xxl text-5xxl lg:max-w-5xl max-w-343 mb-0`}
            >
              {HomePageSectionOneData.title}
            </h2>
            <h3
              className={`maxlg:hidden text-sm text-white font-roboto my-6 leading-snug font-normal lg:max-w-1056`}
            >
              {HomePageSectionOneData.paragraph1}
              <p className="text-sm text-white font-roboto mt-1.5 mb-0">
                {HomePageSectionOneData.paragraph2}
              </p>
            </h3>
            <div className="lg:hidden mt-6">
              <div className={`${isShowMore ? "hidden" : ""}`}>
                <h3
                  className={`text-sm text-white font-roboto leading-snug font-normal mb-3 ${styles.textOverflow}`}
                >
                  {HomePageSectionOneData.paragraph1}
                </h3>
              </div>
              <h3
                className={`${
                  isShowMore ? "" : "hidden"
                } text-sm text-white font-roboto leading-snug font-normal mb-3`}
              >
                {HomePageSectionOneData.paragraph1}
                <p className="text-sm text-white font-roboto mt-1.5 mb-0">
                  {HomePageSectionOneData.paragraph2}
                </p>
              </h3>
              <button
                className={`${isShowMore ? "hidden" : ""} text-white text-sm`}
                onClick={handleShowMore}
              >
                <span className="float-left pr-1.5">Show More</span>
                <ShowMoreIcon className="mt-1" />
              </button>
            </div>
            <div>
              <button
                className={`border border-solid border-primary w-155 h-10 mr-4 text-white bg-primary lg:text-sm xs:text-base maxlg:mt-32`}
              >
                What is BOSS
                <PlayCircleOutlined className={styles.playIcon} />
              </button>
              <button className="border border-solid border-white w-152 h-10 text-white lg:text-sm xs:text-base  maxlg:hidden">
                Book Free Demo
              </button>
            </div>
          </div>
        </section>
      </div>
      <main className={`max-w-1440 h-full ${styles.marginAuto}`}>
        {/* ********************************** */}
        <section
          className={`w-full flex justify-center lg:bg-home-bg lg:h-1035`}
        >
          <div className={`lg:mt-14 lg:w-1122`}>
            <div className={`bg-primary1 py-8`}>
              <h4 className={`text-white font-roboto text-base text-center`}>
                Products
              </h4>
              <h3
                className={`text-white font-roboto lg:text-4xxl text-2xl text-center lg:max-w-882 font-normal maxlg:font-light ${styles.marginAuto}`}
              >
                The leading software for flex & hybrid workspace management and
                tenant engagement
              </h3>
            </div>
            <div className="lg:bg-white bg-bgOne grid grid-cols-1 lg:grid-cols-2 maxlg:p-4">
              <div
                className={`bg-white box-border border border-solid border-default py-8 maxlg:mb-4`}
              >
                <div className={`px-12 maxlg:px-6`}>
                  <h3
                    className={`text-center text-primary text-3xxl maxlg:text-2xl pb-2`}
                  >
                    BOSS Flex
                  </h3>
                  <p
                    className={`text-center font-roboto text-base text-neutral7 lg:w-max-434`}
                  >
                    A property management and tenant engagement platform for
                    flex & hybrid coworking spaces.
                  </p>
                </div>
                <Image
                  src="/images/home-section2-1.png"
                  alt="BOSS Flex"
                  width={560}
                  height={320}
                />
                <div className={`lg:pl-12 maxlg:p-4 maxlg:mb-8 mb-14`}>
                  {SectionTwoBossFlexData.map((item, index) => (
                    <p key={index} className={`mb-0`}>
                      <Image
                        src="/images/vector.png"
                        alt="BOSS Flex"
                        width={16}
                        height={13}
                      />
                      <span className={`text-base text-neutral12 pb-2 pl-2.5`}>
                        {item}
                      </span>
                    </p>
                  ))}
                </div>
                <div className="flex align-center justify-center maxlg:hidden">
                  <button
                    className={`border border-solid border-primary w-155 h-10 text-white bg-primary lg:text-sm xs:text-base mb-6`}
                  >
                    Book Free Demo
                  </button>
                </div>
                <div className="flex align-center justify-center ">
                  <span className={`text-primary text-sm text-center`}>
                    Learn more
                  </span>
                  <Union />
                </div>
              </div>
              <div
                className={`bg-white box-border border lg:border-l-0 border-solid border-default py-8`}
              >
                <div className={`px-12 maxlg:px-6`}>
                  <h3
                    className={`text-center text-primary text-3xxl maxlg:text-2xl pb-2`}
                  >
                    BOSS Tenant Engage
                  </h3>
                  <p
                    className={`text-center font-roboto text-base text-neutral7 lg:w-max-434`}
                  >
                    A tenant engagement platform to delight tenants and boost
                    customer satisfaction.
                  </p>
                </div>
                <Image
                  src="/images/home-section2-2.png"
                  alt="BOSS Flex"
                  width={560}
                  height={320}
                />
                <div className={`lg:pl-12 maxlg:p-4 maxlg:mb-8 mb-14`}>
                  {SectionTwoBossTenantEngage.map((item, index) => (
                    <p key={index} className={`mb-0`}>
                      <Image
                        src="/images/vector.png"
                        alt="BOSS Flex"
                        width={16}
                        height={13}
                      />
                      <span className={`text-base text-neutral12 pb-2 pl-2.5`}>
                        {item}
                      </span>
                    </p>
                  ))}
                </div>
                <div className="flex align-center justify-center maxlg:hidden">
                  <button
                    className={`border border-solid border-primary w-155 h-10 text-white bg-primary lg:text-sm xs:text-base mb-6`}
                  >
                    Book Free Demo
                  </button>
                </div>
                <div className="flex align-center justify-center ">
                  <span className={`text-primary text-sm text-center`}>
                    Learn more
                  </span>
                  <Union />
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* ********************************** */}
        {/* ===== section3 ======= */}
        <section className={`bg-white lg:mt-16 lg:py-10 lg:px-40 py-10 px-4`}>
          <div>
            <p className={`text-xl font-normal mb-4 text-neutral9`}>
              Solutions for you
            </p>
            <div
              className={`lg:grid lg:grid-cols-2 border-b border-solid pb-6 border-borderColor`}
            >
              <div
                className={`lg:text-5xxl text-xl font-roboto font-light lg:max-w-642 max-w-172 italic`}
              >
                Revolutionizing Flex & Hybrid Workspace Management & Business
              </div>
              <div className={`lg:pt-16 lg:pl-12 pt-6 text-base max-w-464`}>
                <p className="font-light">
                  Revolutionize your end-to-end customer journey management —
                  starting all the way from leads acquisition, contract approval
                  workflow to tenant engagement.
                </p>
                <p className={`font-light mb-0`}>
                  Create fulfilling experiences to increase customer retention
                  and revenue.
                </p>
              </div>
            </div>
          </div>
          <div className="maxlg:hidden">
            <Image
              src="/images/home-section3.png"
              alt="BOSS Flex"
              width={1140}
              height={675}
            />
          </div>
          <div className="lg:hidden">
            <Image
              src="/images/home-section3-mobile.png"
              alt="BOSS Flex"
              width={344}
              height={400}
            />
          </div>
        </section>
        {/* ==== section 4 ===== */}
        <section className={`w-full bg-home-section4-bg`}>
          <div className={`bg-primary1 py-8 maxlg:px-4`}>
            <h4 className={`text-white font-roboto text-base lg:text-center`}>
              Highlights
            </h4>
            <h3
              className={`text-white font-roboto lg:text-4xxl text-2xl lg:text-center lg:max-w-882 font-normal maxlg:font-light ${styles.marginAuto}`}
            >
              Flexibility, scalability and user experience to empower business
              growth
            </h3>
          </div>
          <div>
            <Carousel>
              <div>
                <h3>1</h3>
              </div>
              <div>
                <h3>2</h3>
              </div>
            </Carousel>
          </div>
        </section>
        {/* ======= section 5======= */}
        <section className={`w-full lg:py-10 lg:px-40 py-10 px-4`}>
          <div>
            <p className={`text-xl font-normal mb-4 text-neutral9`}>
              Technology
            </p>
            <div className={`lg:grid lg:grid-cols-2`}>
              <div>
                <div
                  className={`lg:text-5xxl text-xl font-roboto font-light lg:max-w-464 max-w-270 italic`}
                >
                  Competitive software powered by the modern engineering
                  infrastructure
                </div>
                <button
                  className={`lg:mt-28 border border-solid border-primary w-155 h-10 text-white bg-primary lg:text-sm xs:text-base mb-6 maxlg:hidden`}
                >
                  Book Free Demo
                </button>
              </div>
              <div className={`text-base maxlg:pt-8 `}>
                {HomePageSectionFiveData.map((item, index) => (
                  <div
                    key={index}
                    className={`flex  ${index < 3 ? "mb-6" : ""}`}
                  >
                    <div>
                      <Image
                        src={item.url}
                        alt="BOSS Flex"
                        width={80}
                        height={80}
                      />
                    </div>
                    <div className={`pb-6 ml-4 border-b border-solid lg:w-464`}>
                      <h3
                        className={`lg:text-3xxl text-xl font-normal text-neutral12`}
                      >
                        {item.title}
                      </h3>
                      <p className={`text-neutral8 mb-0 text-base font-normal`}>
                        {item.content}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
        <section className="flex justify-center align-bottom">
          <Image
            src="/images/breakImage.png"
            alt="BOSS Flex"
            layout="intrinsic"
            width={1440}
            height={480}
          />
        </section>
      </main>
    </div>
  );
}
