import type { NextPage } from "next";
import Head from "next/head";

interface ChildProps {
  name: string;
}
interface StaticProps {
  data: ChildProps;
}
// 静态生成example
function Child(props: ChildProps) {
  return (
    <div>
      <Head>
        <title>child page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{props?.name}</div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data: ChildProps = { name: "123@" }
  return {
    props: data, // will be passed to the page component as props
  };
}
export default Child;
